# Generated by Django 4.2.2 on 2023-06-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transactions_delete_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
