# Generated by Django 4.2.2 on 2023-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transactions_delete_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='ref_id',
            field=models.CharField(max_length=50),
        ),
    ]
